"""The M-step's weighted cross entropy, against the golden.

The golden is not "what I think equation 11 gives": it is generated by calling
Stoix's REAL `compute_cross_entropy_loss` (imported, not rewritten) in its particle
form, and checking right there that it matches the dense form we implement here.
The measured differences ranged from 1e-9 to 5e-8, that is, float32 noise.

That matters because choosing the dense form might look like a deviation, and it is
not: since the root actions repeat across particles,

    SUM_n w_n log pi(a_n)  =  SUM_a q(a) log pi(a)

is the same sum regrouped. The golden turns that argument into a number.
"""

from std.gpu.host import DeviceContext
from std.math import log

from ops.buffers import zero_buffer
from ops.common import dtype, NEG_INF
from ops.softmax import log_softmax_rows
from networks.actor_loss import cross_entropy_rows, entropy_rows, kl_rows
from tests.golden_io import read_f32
from tests.helpers import upload, download, filled, assert_close

comptime TOL = Scalar[dtype](2e-5)
comptime GOLDEN = String("tests/golden/")
comptime NUM_ACTIONS = 9
comptime TPB_ROW = 32


def mean_of(values: List[Scalar[dtype]], n: Int) -> Scalar[dtype]:
    total = Scalar[dtype](0)
    for i in range(n):
        total += values[i]
    return total / Scalar[dtype](n)


def check_case(ctx: DeviceContext, name: String, batch: Int) raises:
    """One golden case: from the log-softmax to the per-state loss and to the mean."""
    tag = GOLDEN + "ce_" + name + "_"
    logits = upload[dtype](ctx, read_f32(tag + "logits.bin"))
    q = upload[dtype](ctx, read_f32(tag + "q.bin"))
    mask = read_f32(tag + "mask.bin")

    # 1. log pi, computed directly and not as log(softmax).
    log_pi = zero_buffer[dtype](ctx, batch * NUM_ACTIONS)
    ctx.enqueue_function[log_softmax_rows[TPB_ROW], log_softmax_rows[TPB_ROW]](
        log_pi.unsafe_ptr(), logits.unsafe_ptr(), NUM_ACTIONS,
        grid_dim=batch, block_dim=TPB_ROW)
    ctx.synchronize()

    want_logpi = read_f32(tag + "logpi.bin")
    got_logpi = download[dtype](log_pi, batch * NUM_ACTIONS)
    for i in range(batch * NUM_ACTIONS):
        if mask[i] == Scalar[dtype](0):
            # On the illegal ones all that is required is that it be
            # "effectively minus infinity". The exact bit pattern of a saturated
            # value is not the contract; that it contributes nothing to the log is.
            if got_logpi[i] > Scalar[dtype](-1e30):
                raise Error(name, ": el log pi de la casilla ilegal ", i,
                            " deberia ser muy negativo y vale ", got_logpi[i])
        else:
            assert_close(got_logpi[i], want_logpi[i], TOL,
                         String(name, " log pi ", i))

    # 2. Each state's loss and their mean.
    per_state = zero_buffer[dtype](ctx, batch)
    cross_entropy_rows(ctx, per_state, q, log_pi, batch, NUM_ACTIONS)
    ctx.synchronize()

    want_per = read_f32(tag + "per_state.bin")
    got_per = download[dtype](per_state, batch)
    for b in range(batch):
        assert_close(got_per[b], want_per[b], TOL,
                     String(name, " perdida del estado ", b))

    # 3. La descomposicion H(q,pi) = H(q) + KL(q||pi).
    h = zero_buffer[dtype](ctx, batch)
    kl = zero_buffer[dtype](ctx, batch)
    entropy_rows(ctx, h, q, batch, NUM_ACTIONS)
    kl_rows(ctx, kl, per_state, h, batch)
    ctx.synchronize()

    want_h = read_f32(tag + "entropy.bin")
    want_kl = read_f32(tag + "kl.bin")
    got_h = download[dtype](h, batch)
    got_kl = download[dtype](kl, batch)
    for b in range(batch):
        assert_close(got_h[b], want_h[b], TOL, String(name, " H(q) del estado ", b))
        assert_close(got_kl[b], want_kl[b], TOL, String(name, " KL del estado ", b))
        # The KL is a divergence: never negative.
        if got_kl[b] < Scalar[dtype](-1e-5):
            raise Error(name, ": KL negativa en el estado ", b, ": ", got_kl[b])
        # And the decomposition has to close exactly.
        assert_close(got_h[b] + got_kl[b], got_per[b], TOL,
                     String(name, " H(q)+KL deberia dar la perdida en ", b))

    want_loss = read_f32(tag + "loss.bin")
    got_loss = mean_of(got_per, batch)
    assert_close(got_loss, want_loss[0], TOL, String(name, " perdida media"))
    print("PASS ce ", name, " (B=", batch, "): perdida ", got_loss,
          " = H(q) ", mean_of(got_h, batch), " + KL ", mean_of(got_kl, batch))


def test_matches_stoix_golden(ctx: DeviceContext) raises:
    """The three cases: small batch, ragged batch, and the large N we use.

    Each one's golden was generated by comparing the dense form against Stoix's
    `compute_cross_entropy_loss`, so passing this is passing both.
    """
    check_case(ctx, "small", 3)
    check_case(ctx, "mid", 7)
    check_case(ctx, "big", 32)
    # 70 rows is three blocks with TPB=32 and the last one half full. Without this
    # case the kernel's `row >= n_rows` guard would never execute: every other batch
    # fits in one block. It is the same blind spot that bit me in E1.7 and E1.9, so
    # now it is on the fixed list.
    check_case(ctx, "multiblock", 70)


def test_zero_weight_terms_do_not_produce_nan(ctx: DeviceContext) raises:
    """A term with q = 0 and a GENUINE log pi = -inf does not give NaN.

    In the golden the illegal cells sit at the most negative finite float32, so
    0 * that gives 0 and the kernel's guard never gets demonstrated. Here the worst
    case is forced: an authentic -inf. Without the `if w != 0`, IEEE gives
    0 * (-inf) = NaN, and that NaN does not fail loudly -- it propagates to the
    loss, to the gradient and to the weights, and training breaks without anybody
    knowing where.

    It is exactly the kind of fault this project has already been bitten by once
    (the workspace bug in A6), so it comes with a test.
    """
    batch = 2
    inf_neg = Scalar[dtype](-1) / Scalar[dtype](0)     # -inf autentico

    lp = List[Scalar[dtype]]()
    qs = List[Scalar[dtype]]()
    for _ in range(batch):
        for a in range(NUM_ACTIONS):
            legal = a < 3                      # solo las tres primeras
            lp.append(Scalar[dtype](-1.0986123) if legal else inf_neg)
            qs.append(Scalar[dtype](1) / Scalar[dtype](3) if legal
                      else Scalar[dtype](0))
    log_pi = upload[dtype](ctx, lp)
    q = upload[dtype](ctx, qs)
    per_state = filled[dtype](ctx, batch, Scalar[dtype](-99))

    cross_entropy_rows(ctx, per_state, q, log_pi, batch, NUM_ACTIONS)
    ctx.synchronize()
    got = download[dtype](per_state, batch)

    for b in range(batch):
        if got[b] != got[b]:                   # nan != nan
            raise Error("el estado ", b, " dio NaN: falta el guard de q == 0")
        # Tres acciones equiprobables: -SUM (1/3)*log(1/3) = log(3) = 1.0986123
        assert_close(got[b], Scalar[dtype](1.0986123), TOL,
                     String("perdida del estado ", b))
    print("PASS los terminos con q=0 se saltan y un -inf de verdad no da NaN")


def loss_of(ctx: DeviceContext, log_pi_vals: List[Scalar[dtype]],
            q_vals: List[Scalar[dtype]]) raises -> Scalar[dtype]:
    """The loss of a single state with 3 legal actions and 6 masked.

    At module level and not nested because in Mojo 1.0.0b1 a nested function cannot
    capture `ctx` nor a `List` from the enclosing scope.
    """
    lp = List[Scalar[dtype]]()
    qs = List[Scalar[dtype]]()
    for a in range(NUM_ACTIONS):
        if a < 3:
            lp.append(log_pi_vals[a]); qs.append(q_vals[a])
        else:
            lp.append(NEG_INF); qs.append(Scalar[dtype](0))
    log_pi = upload[dtype](ctx, lp)
    q = upload[dtype](ctx, qs)
    out = zero_buffer[dtype](ctx, 1)
    cross_entropy_rows(ctx, out, q, log_pi, 1, NUM_ACTIONS)
    ctx.synchronize()
    return download[dtype](out, 1)[0]


def test_loss_is_minimised_when_pi_equals_q(ctx: DeviceContext) raises:
    """The loss is minimal when pi matches q, and grows as it moves away.

    It is the property that makes optimising this meaningful: equation 11 projects
    q onto the network, so the minimum has to be at pi = q. If the sign were
    inverted, or if an extra log had slipped in, the loss would be minimal
    somewhere else and training would push the wrong way -- and a golden does NOT
    detect that, because a golden only checks one point.

    The loss at pi = q is compared against the entropy of q (its exact value at the
    minimum) and against two deviated policies.
    """
    q_vals = List[Scalar[dtype]]()
    q_vals.append(0.5); q_vals.append(0.3); q_vals.append(0.2)

    # pi = q: the loss is exactly the entropy of q.
    at_min = List[Scalar[dtype]]()
    entropy = Scalar[dtype](0)
    for a in range(3):
        at_min.append(log(q_vals[a]))
        entropy += -q_vals[a] * log(q_vals[a])
    got_min = loss_of(ctx, at_min, q_vals)
    assert_close(got_min, entropy, Scalar[dtype](1e-5),
                 "en pi = q la perdida tiene que valer la entropia de q")

    # Two deviations: the uniform one, and another that inverts the preference order.
    uniform = List[Scalar[dtype]]()
    for _ in range(3):
        uniform.append(log(Scalar[dtype](1) / Scalar[dtype](3)))
    got_uniform = loss_of(ctx, uniform, q_vals)

    flipped = List[Scalar[dtype]]()
    flipped.append(log(Scalar[dtype](0.2)))
    flipped.append(log(Scalar[dtype](0.3)))
    flipped.append(log(Scalar[dtype](0.5)))
    got_flipped = loss_of(ctx, flipped, q_vals)

    if got_uniform <= got_min:
        raise Error("la uniforme deberia perder mas que pi=q: ", got_uniform,
                    " vs ", got_min)
    if got_flipped <= got_uniform:
        raise Error("invertir el orden deberia ser peor que la uniforme: ",
                    got_flipped, " vs ", got_uniform)
    print("PASS la perdida es minima en pi=q (=", got_min,
          "), uniforme ", got_uniform, ", invertida ", got_flipped)


def test_kl_is_zero_exactly_when_pi_equals_q(ctx: DeviceContext) raises:
    """The KL is 0 at pi=q and positive as soon as it departs.

    It is what makes the diagnostic useful: the CROSS ENTROPY at pi=q is H(q),
    which can be any number and moreover changes between iterations because q is
    produced by the search. The KL has a zero with a meaning -- "the actor
    reproduces exactly what the search says" -- and that zero is the same across
    every configuration, so it can indeed be compared between arms.
    """
    q_vals = List[Scalar[dtype]]()
    q_vals.append(0.5); q_vals.append(0.3); q_vals.append(0.2)

    at_min = List[Scalar[dtype]]()
    for a in range(3):
        at_min.append(log(q_vals[a]))
    uniform = List[Scalar[dtype]]()
    for _ in range(3):
        uniform.append(log(Scalar[dtype](1) / Scalar[dtype](3)))

    ce_min = loss_of(ctx, at_min, q_vals)
    ce_uni = loss_of(ctx, uniform, q_vals)

    # H(q) with the kernel, over the same vector padded to 9 actions.
    qs = List[Scalar[dtype]]()
    for a in range(NUM_ACTIONS):
        qs.append(q_vals[a] if a < 3 else Scalar[dtype](0))
    q = upload[dtype](ctx, qs)
    h = zero_buffer[dtype](ctx, 1)
    entropy_rows(ctx, h, q, 1, NUM_ACTIONS)
    ctx.synchronize()
    got_h = download[dtype](h, 1)[0]

    # H(q) a mano: 1.0296531 para (0.5, 0.3, 0.2).
    assert_close(got_h, Scalar[dtype](1.0296531), TOL, "H(q) de (0.5,0.3,0.2)")
    assert_close(ce_min - got_h, Scalar[dtype](0), Scalar[dtype](1e-5),
                 "la KL en pi=q tiene que ser 0")
    if ce_uni - got_h <= Scalar[dtype](0):
        raise Error("la KL de la uniforme deberia ser positiva: ", ce_uni - got_h)
    print("PASS KL = 0 en pi=q (perdida ", ce_min, " = H(q) ", got_h,
          ") y ", ce_uni - got_h, " con la uniforme")


def test_entropy_edge_cases(ctx: DeviceContext) raises:
    """H of a one-hot is 0 and H of a uniform over k is log(k).

    The two extremes, which are what fix the scale. The one-hot is also the
    dangerous case: q is 1 on one cell and 0 on the other eight, so if the `w > 0`
    guard were missing there would be eight 0*log(0) = NaN terms and H would come
    out NaN instead of 0. And it is a REAL case: our corrected readout's q comes out
    nearly one-hot (we measured 0.9999999).
    """
    # Row 0: one-hot. Row 1: uniform over 3. Row 2: uniform over all 9.
    qs = List[Scalar[dtype]]()
    for a in range(NUM_ACTIONS):
        qs.append(Scalar[dtype](1) if a == 4 else Scalar[dtype](0))
    for a in range(NUM_ACTIONS):
        qs.append(Scalar[dtype](1) / Scalar[dtype](3) if a < 3
                  else Scalar[dtype](0))
    for _ in range(NUM_ACTIONS):
        qs.append(Scalar[dtype](1) / Scalar[dtype](NUM_ACTIONS))

    q = upload[dtype](ctx, qs)
    h = zero_buffer[dtype](ctx, 3)
    entropy_rows(ctx, h, q, 3, NUM_ACTIONS)
    ctx.synchronize()
    got = download[dtype](h, 3)

    if got[0] != got[0]:
        raise Error("H de una one-hot salio NaN: falta el guard de q == 0")
    assert_close(got[0], Scalar[dtype](0), TOL, "H de una one-hot")
    assert_close(got[1], log(Scalar[dtype](3)), TOL, "H de la uniforme sobre 3")
    assert_close(got[2], log(Scalar[dtype](NUM_ACTIONS)), TOL,
                 "H de la uniforme sobre 9")
    print("PASS H(one-hot)=0 sin NaN, H(uniforme sobre k)=log k")


def main() raises:
    with DeviceContext() as ctx:
        test_matches_stoix_golden(ctx)
        test_zero_weight_terms_do_not_produce_nan(ctx)
        test_loss_is_minimised_when_pi_equals_q(ctx)
        test_kl_is_zero_exactly_when_pi_equals_q(ctx)
        test_entropy_edge_cases(ctx)
