"""The linear layer against the numpy golden.

Three cases generated by tests/golden/gen/gen_linear.py, chosen on purpose:

  case0  (4, 18) @ (18, 64)   the critic's real first layer
  case1  (64, 64) @ (64, 64)  several tiles across all three dimensions
  case2  (7, 5) @ (5, 3)      ragged: no dimension is a multiple of the tile, so
                              every guard gets exercised

The ragged case is the one that matters: our real dimensions (18 inputs, a batch
of particles) are almost never multiples of 16, so the edges get exercised on
every real call.
"""

from std.gpu.host import DeviceContext
from std.math import abs, sqrt

from ops.common import dtype
from networks.linear import linear_forward, TILE
from tests.golden_io import read_f32
from tests.helpers import upload, zeros, download

comptime GOLDEN = String("tests/golden/")


def check_case(ctx: DeviceContext, which: Int, m: Int, k: Int, n: Int) raises:
    """Runs the layer over one golden case and compares against numpy."""
    x = read_f32(GOLDEN + "linear" + String(which) + "_x.bin")
    w = read_f32(GOLDEN + "linear" + String(which) + "_w.bin")
    b = read_f32(GOLDEN + "linear" + String(which) + "_b.bin")
    want = read_f32(GOLDEN + "linear" + String(which) + "_y.bin")

    if len(x) != m * k or len(w) != k * n or len(b) != n or len(want) != m * n:
        raise Error("el golden del caso ", which, " no tiene las shapes esperadas")

    xd = upload[dtype](ctx, x)
    wd = upload[dtype](ctx, w)
    bd = upload[dtype](ctx, b)
    yd = zeros[dtype](ctx, m * n)

    linear_forward(ctx, yd, xd, wd, bd, m, k, n)
    ctx.synchronize()
    got = download[dtype](yd, m * n)

    # Tolerance RELATIVE to the problem's scale: summing k terms in float32 carries
    # error proportional to sqrt(k), and the summation order is not the same as
    # numpy's (here it accumulates by tiles). Asking for 1e-6 absolute would be
    # asking for more precision than survives reordering a sum.
    tol = Scalar[dtype](1e-5) * sqrt(Scalar[dtype](k))
    worst = Scalar[dtype](0)
    worst_at = 0
    for i in range(m * n):
        d = abs(got[i] - want[i])
        if d > worst:
            worst = d
            worst_at = i
    if worst > tol:
        raise Error("caso ", which, ": la mayor diferencia es ", worst,
                    " en el indice ", worst_at, " (got=", got[worst_at],
                    " want=", want[worst_at], ", tolerancia ", tol, ")")

    print("      case", which, " (", m, "x", k, ") @ (", k, "x", n,
          ")  error max", worst, " (tol", tol, ")")


def test_against_numpy(ctx: DeviceContext) raises:
    """The golden's three cases."""
    check_case(ctx, 0, 4, 18, 64)
    check_case(ctx, 1, 64, 64, 64)
    check_case(ctx, 2, 7, 5, 3)
    print("PASS la capa lineal coincide con numpy en los tres casos")


def test_bias_is_added_once(ctx: DeviceContext) raises:
    """With W = 0, the output has to be exactly the bias.

    It separates two faults the golden cannot tell apart: if the bias were added
    twice (once per tile, say) the error would hide inside the matmul's noise, but
    here it would come out exactly double.
    """
    m = 5
    k = 20      # > TILE, that is, two turns of the tile loop
    n = 3
    xs = List[Scalar[dtype]]()
    for i in range(m * k):
        xs.append(Scalar[dtype](i % 7) - 3.0)      # anything at all, W=0 cancels it
    ws = List[Scalar[dtype]]()
    for _ in range(k * n):
        ws.append(Scalar[dtype](0))
    bs = List[Scalar[dtype]]()
    for j in range(n):
        bs.append(Scalar[dtype](j) + 0.5)

    yd = zeros[dtype](ctx, m * n)
    linear_forward(ctx, yd, upload[dtype](ctx, xs), upload[dtype](ctx, ws),
                   upload[dtype](ctx, bs), m, k, n)
    ctx.synchronize()
    got = download[dtype](yd, m * n)

    for r in range(m):
        for c in range(n):
            v = got[r * n + c]
            if abs(v - bs[c]) > Scalar[dtype](1e-6):
                raise Error("con W=0 la salida deberia ser el bias: fila ", r,
                            " col ", c, " dio ", v, " y el bias es ", bs[c])
    print("PASS el bias se suma exactamente una vez (W=0 -> y = b)")


def test_identity_passes_input_through(ctx: DeviceContext) raises:
    """With W = identity and b = 0, the output is the input.

    It checks the matmul's ORIENTATION, which is what the golden cannot tell apart
    well: if rows were confused with columns when indexing W, the result would
    still look like plausible numbers. With the identity, a transposition shows up
    instantly.

    K = 20 > TILE on purpose: each row's 1 falls in a different tile.
    """
    n = 20
    m = 3
    xs = List[Scalar[dtype]]()
    for r in range(m):
        for c in range(n):
            xs.append(Scalar[dtype](r * 100 + c))   # all different
    ws = List[Scalar[dtype]]()
    for i in range(n):
        for j in range(n):
            ws.append(Scalar[dtype](1) if i == j else Scalar[dtype](0))
    bs = List[Scalar[dtype]]()
    for _ in range(n):
        bs.append(Scalar[dtype](0))

    yd = zeros[dtype](ctx, m * n)
    linear_forward(ctx, yd, upload[dtype](ctx, xs), upload[dtype](ctx, ws),
                   upload[dtype](ctx, bs), m, n, n)
    ctx.synchronize()
    got = download[dtype](yd, m * n)

    for i in range(m * n):
        if abs(got[i] - xs[i]) > Scalar[dtype](1e-6):
            raise Error("W=identidad deberia devolver la entrada: indice ", i,
                        " dio ", got[i], " y la entrada era ", xs[i])
    print("PASS W = identidad devuelve la entrada (la orientacion es correcta)")


def main() raises:
    with DeviceContext() as ctx:
        test_against_numpy(ctx)
        test_bias_is_added_once(ctx)
        test_identity_passes_input_through(ctx)
