"""Softmax and logsumexp against the numpy golden.

The golden is generated by tests/golden/gen/gen_softmax.py. The rows are not
entirely random: the first four are set by hand to blow up a naive implementation.
  row 0: all 0      -> exactly uniform softmax, 1/COLS
  row 1: all +1000  -> exp(1000) = inf. Without subtracting the max it gives inf/inf = nan
  row 2: one +1000  -> nearly one-hot softmax
  row 3: all -1000  -> exp(-1000) = 0. Without subtracting the max it gives 0/0 = nan

And on top of that a block of WIDE rows (wide_*), with more columns than threads
per block. Until E2.2 this file only tested COLS=16 with TPB=32, so the `i += TPB`
loop the kernels use to walk the row **always went round exactly once and the
striding path was never executed**. WIDE_COLS=100 gives three full turns and a
partial one, and row 1 puts its maximum in the LAST column: if the striding did not
reach the end, the maximum would come out wrong and the whole softmax with it.
"""

from std.gpu.host import DeviceContext
from std.math import abs, log

from ops.common import dtype
from ops.softmax import log_softmax_rows, softmax_rows, logsumexp_rows
from tests.golden_io import read_f32
from tests.helpers import upload, zeros, download, assert_close

comptime TPB = 32
comptime WIDE_ROWS = 4
comptime WIDE_COLS = 100
comptime ROWS = 6
comptime COLS = 16
comptime TOL = Scalar[dtype](1e-6)


def main() raises:
    x = read_f32("tests/golden/softmax_in.bin")
    want_softmax = read_f32("tests/golden/softmax_out.bin")
    want_lse = read_f32("tests/golden/logsumexp_out.bin")

    if len(x) != ROWS * COLS:
        raise Error("golden softmax_in con tamano raro: ", len(x),
                    " (regenerar con gen_softmax.py?)")

    with DeviceContext() as ctx:
        a = upload[dtype](ctx, x)
        sm = zeros[dtype](ctx, ROWS * COLS)
        lse = zeros[dtype](ctx, ROWS)

        ctx.enqueue_function[softmax_rows[TPB], softmax_rows[TPB]](
            sm.unsafe_ptr(), a.unsafe_ptr(), COLS, grid_dim=ROWS, block_dim=TPB)
        ctx.enqueue_function[logsumexp_rows[TPB], logsumexp_rows[TPB]](
            lse.unsafe_ptr(), a.unsafe_ptr(), COLS, grid_dim=ROWS, block_dim=TPB)
        ctx.synchronize()

        got_sm = download[dtype](sm, ROWS * COLS)
        got_lse = download[dtype](lse, ROWS)

    # Element by element against numpy.
    for r in range(ROWS):
        for c in range(COLS):
            assert_close(got_sm[r * COLS + c], want_softmax[r * COLS + c], TOL,
                         String("softmax fila=", r, " col=", c))
    print("PASS softmax_rows vs numpy (", ROWS, "filas x", COLS, ")")

    # The uniform row has to give exactly 1/COLS.
    uniform = Scalar[dtype](1.0) / Scalar[dtype](COLS)
    for c in range(COLS):
        assert_close(got_sm[c], uniform, TOL, String("fila uniforme col=", c))
    print("PASS softmax fila uniforme = 1/", COLS)

    # Every row has to sum to 1, including the +-1000 ones. This check is the one
    # that detects the overflow: if exp overflows, the row sums to nan.
    for r in range(ROWS):
        total = Scalar[dtype](0)
        for c in range(COLS):
            total += got_sm[r * COLS + c]
        assert_close(total, 1.0, Scalar[dtype](1e-5),
                     String("la fila ", r, " no suma 1"))
    print("PASS softmax suma 1 por fila (sin overflow en +-1000)")

    # The logsumexp is compared with a relative tolerance. The +1000 row gives
    # ~1002.77, and at that magnitude float32's ulp is already ~6e-5: asking for
    # 1e-6 absolute would be asking for more precision than exists.
    for r in range(ROWS):
        scale = abs(want_lse[r])
        if scale < 1.0:
            scale = Scalar[dtype](1.0)
        rel = abs(got_lse[r] - want_lse[r]) / scale
        if rel > TOL:
            raise Error("logsumexp fila=", r, ": got=", got_lse[r],
                        " want=", want_lse[r], " (error relativo=", rel, ")")
    print("PASS logsumexp_rows vs numpy")

    # The new tests open their own context: the `with` above has already closed
    # and this block's checks run on the host.
    with DeviceContext() as ctx2:
        test_log_softmax_matches_log_of_softmax(ctx2)
        test_wide_rows(ctx2)


def test_wide_rows(ctx: DeviceContext) raises:
    """Rows wider than the block: the three kernels' striding path."""
    x = read_f32("tests/golden/wide_in.bin")
    want_sm = read_f32("tests/golden/wide_softmax.bin")
    want_lse = read_f32("tests/golden/wide_logsumexp.bin")
    want_lsm = read_f32("tests/golden/wide_logsoftmax.bin")

    n = WIDE_ROWS * WIDE_COLS
    a = upload[dtype](ctx, x)
    sm = zeros[dtype](ctx, n)
    lse = zeros[dtype](ctx, WIDE_ROWS)
    lsm = zeros[dtype](ctx, n)

    ctx.enqueue_function[softmax_rows[TPB], softmax_rows[TPB]](
        sm.unsafe_ptr(), a.unsafe_ptr(), WIDE_COLS,
        grid_dim=WIDE_ROWS, block_dim=TPB)
    ctx.enqueue_function[logsumexp_rows[TPB], logsumexp_rows[TPB]](
        lse.unsafe_ptr(), a.unsafe_ptr(), WIDE_COLS,
        grid_dim=WIDE_ROWS, block_dim=TPB)
    ctx.enqueue_function[log_softmax_rows[TPB], log_softmax_rows[TPB]](
        lsm.unsafe_ptr(), a.unsafe_ptr(), WIDE_COLS,
        grid_dim=WIDE_ROWS, block_dim=TPB)
    ctx.synchronize()

    got_sm = download[dtype](sm, n)
    got_lse = download[dtype](lse, WIDE_ROWS)
    got_lsm = download[dtype](lsm, n)

    for i in range(n):
        assert_close(got_sm[i], want_sm[i], Scalar[dtype](1e-6),
                     String("wide softmax ", i))
        assert_close(got_lsm[i], want_lsm[i], Scalar[dtype](1e-4),
                     String("wide log softmax ", i))
    for r in range(WIDE_ROWS):
        scale = abs(want_lse[r])
        if scale < 1.0:
            scale = Scalar[dtype](1.0)
        rel = abs(got_lse[r] - want_lse[r]) / scale
        if rel > TOL:
            raise Error("wide logsumexp fila=", r, ": got=", got_lse[r],
                        " want=", want_lse[r])
        total = Scalar[dtype](0)
        for c in range(WIDE_COLS):
            total += got_sm[r * WIDE_COLS + c]
        assert_close(total, 1.0, Scalar[dtype](1e-5),
                     String("la fila ancha ", r, " no suma 1"))
    print("PASS filas de ", WIDE_COLS, " columnas (striding con TPB=", TPB, ")")


def test_log_softmax_matches_log_of_softmax(ctx: DeviceContext) raises:
    """The log_softmax matches the golden, and matches log(softmax) where the
    latter does not underflow.

    The second part is what justifies having a separate kernel: on the normal rows
    the two routes agree, but on the -1000 row the softmax saturates to tiny values
    and its log loses precision, whereas the direct log_softmax keeps the exact
    value. It is checked where the softmax is healthy (> 1e-6) and left out where
    it is not, which is precisely the case that motivates the kernel.
    """
    x = read_f32("tests/golden/softmax_in.bin")
    want_lsm = read_f32("tests/golden/logsoftmax_out.bin")
    n = ROWS * COLS

    a = upload[dtype](ctx, x)
    lsm = zeros[dtype](ctx, n)
    sm = zeros[dtype](ctx, n)
    ctx.enqueue_function[log_softmax_rows[TPB], log_softmax_rows[TPB]](
        lsm.unsafe_ptr(), a.unsafe_ptr(), COLS, grid_dim=ROWS, block_dim=TPB)
    ctx.enqueue_function[softmax_rows[TPB], softmax_rows[TPB]](
        sm.unsafe_ptr(), a.unsafe_ptr(), COLS, grid_dim=ROWS, block_dim=TPB)
    ctx.synchronize()

    got_lsm = download[dtype](lsm, n)
    got_sm = download[dtype](sm, n)

    for i in range(n):
        assert_close(got_lsm[i], want_lsm[i], Scalar[dtype](1e-4),
                     String("log softmax ", i))
        if got_sm[i] > Scalar[dtype](1e-6):
            assert_close(got_lsm[i], log(got_sm[i]), Scalar[dtype](1e-3),
                         String("log_softmax vs log(softmax) en ", i))
    print("PASS log_softmax_rows vs numpy, y coincide con log(softmax) donde "
          "este no pierde precision")
